### ISSUE TITLE
prettier in multiple package.json file

### ISSUE THREAD

**Issue by danieltorrer** [abetoots/epic-stack-turborepo#1]
I see that the root package.json file has defined `prettier` and `prettier-plugin-tailwind` https://github.com/abetoots/epic-stack-turborepo/blob/main/package.json#L20 but also the folder with the epic-stack has the same devdeps https://github.com/abetoots/epic-stack-turborepo/blob/main/apps/web/package.json#L150. 

Is this correct or it's just a typo?

Thanks for setting up this repo, its helping me a lot to understand how turborepo works :)

**Comment by abetoots** [comment]
apologies i must've missed the notif for this. glad the repo is of help. you're right. each app should be responsible for their own formatting and if you want a prettier config to be shared it should be in defined in `packages`.

fixed by 6a66c3b
